### PR TITLE
Applicative, Monoid, HeytingAlgebra instances

### PR DESCRIPTION
**Pull request by MonoidMusician**
The previous `Applicative` wasn't law-abiding: `(pure 1 <|> pure 2) <* pure unit` did not equal `pure 1 <|> pure 2`, it was just `pure 2`

As an example of how it worked:
```purescript
> subscribe (Tuple <$> (pure 1 <|> pure 2) <*> (pure 3 <|> pure 4)) logShow
(Tuple 2 3)
(Tuple 2 4)
```

Instead, we will manually track the `bang`s (initial values) that are sent on each event and manually replay them in the sequence that matches how `Apply Array` does it.

Note that this still keeps the “weird” behavior for other simultaneous events after initial subscription:
```purescript
do
  rf <- Ref.new []
  { push, event } <- Event.create
  let
    double = lift2 (+) event event
  unsub <- Event.subscribe double \i -> Ref.modify_ (cons i) rf
  push 2
  push 1
  o <- Ref.read rf
  o `shouldEqual` [ 2, 3, 4 ]
```

It would require knowing how to group events into ticks.
However, this is okay: it should still be law abiding.
In particular, associativity is the only law at risk (now that identity of `pure` is taken care of), and it should be fine: the subscriptions will happen in the same order and the same state will be maintained.

I think these transient events are something that we'll just have to live with until there's a complete overhaul of event sources to allow grouping ticks like that. It should be benign for most usages (if they're idempotent, like setting attributes in Deku).

### CODE REVIEW

**Comment by mikesol** [comment]
Sorry that I didn't see this before, not sure why. I'll review this later today!

**Review by mikesol — COMMENTED** [review]
This looks great!

A couple requests:

- Could you keep `bang` as an alias for `pure` that's exported in all the same places (if possible) with a deprecation warning. We can add that folks have _n_ months/versions to migrate stuff over.
- The changes to the test look great - for apply, could you make them a bit more schematic? As you pointed out, the behavior for transients is not ideal, but we should try to exhaustively document them in the tests so that they're predictable. It'd be nice if there were 4-7 tests that covered the surface area of potential outcomes so that, after reading them, someone could use `<*>` basically anywhere and reason about what it's doing.

After this we're good to go!

**Comment by mikesol** [comment]
@MonoidMusician is it ok if I hack at this branch a bit? I have some time this evening & tomorrow & I can add those tests. Just let me know!

**Comment by MonoidMusician** [comment]
Yeah sounds good

**Comment by mikesol** [comment]
@MonoidMusician done, could you give it a look over? If all looks good I'll merge & make a PR to the package set with new versions of hyrule + various libs that depend on hyrule.

**Comment by MonoidMusician** [comment]
Yes looks good! Somehow forgot to look it over earlier today 😅

**Pull request merged**
