### PR TITLE
Rewrites event to be more performant

### PR DESCRIPTION
**Pull request by mikesol**
This uses a logic similar to the `Zora` monad but encodes it entirely in `Event`.
It stays fast by implementing a single check in `makeEvent`.

### CODE REVIEW

**Comment by mikesol** [comment]
To expand a bit upon the idea:

The basic functionality is exactly the same as Zora - we either run something that's pure or impure.

The way it's done here, though, is that it threads a boolean that represents purity (`true` is pure, `false` is not) from the subscription down through the events. Then, `makeEvent` checks this boolean and, if it is `true`, does not execute its code. `makePureEvent` _always_ (it does not check the boolean) because it is `ST`, so it will work by definition in `Effect`.

The tricky bit comes when there's some code that is in `ST` but it needs to subscribe to effectful events. We want to say "in an effectful context, it's ok to call subscribe." But the problem is that we're in `ST`, and we can't call subscribe, which has the signature `Event a -> (a -> Effect Unit) -> Effect (Effect Unit)`. The solution is `makeLemmingEvent`. This _injects_ a subscriber into the function, and the subscriber inherits the purity of the upstream subscriber (you can see that in the implementation). This allows for `ST` to subscribe to something with type `Effect`. "Heresy", you say! "Because we're in ST, that should never happen!" True, it shouldn't, but because the effectful function will be muted in a pure context thanks to the implementation of `makeEvent`, this is always a safe operation!

**Review by PureFunctor — CHANGES_REQUESTED** [review]
Aside from a few nits, this looks pretty good.

I also think the `unsafeCoerce`s can be lifted onto let bindings, and they'll be optimized away just fine. It should make it easier to follow the code that way.

In general, this looks like a really cool way to fuse Zora into Event! Now that they're back to being monomorphic though, is there really anything that we'll miss?

**Comment by mikesol** [comment]
>

**Comment by mikesol** [comment]
>

**Comment by mikesol** [comment]
> In general, this looks like a really cool way to fuse Zora into Event! Now that they're back to being monomorphic though, is there really anything that we'll miss?

[apologies for closing and reopening, I don't know how to use GitHub...]

Your question is spot-on: I don't know the answer, but that's what makes me most hesitant about merging this. The commit takes a lot of our learnings & developments from the past few months (`Always`, `Zora`, how Deku apps run in the wild, a new backend optimizer) and pushes the framework in a direction that fits with those learnings at the expense of generality. At the same time, it's "back where it started" in that we're back to `Effect` again (with a bit of `ST` here and there), so it's not too out-of-left-field.

**Pull request merged**
